apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    REPLACE ME with the JSON output of "oc extract --namespace openshift-config secret/pull-secret --keys .dockerconfigjson --to -"
