apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: awx-resource-operator
  namespace: awx-resource-operator
spec:
  channel: release-0.1
  name: awx-resource-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
