targetConfigs:
- url:  http://svc-gitea:PASSWORD@CHANGEIPADDRESS:3000/svc-gitea/openshift-virtualization-gitops
  filetransfer:
  - name: copy-vars
    targetPath: inventories/virtual-lab/host_vars
    destinationDirectory: /tmp/qubinode-test
    schedule: "*/1 * * * *"
  branch: main
targetConfigs:
- url: http://github.com/containers/fetchit
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: main